import streamlit as st


IMPORTANCE_LABELS = {
    "high": "High importance",
    "medium": "Medium importance",
    "low": "Low importance",
}


def render_recommendation_items(
    title: str,
    items: list[dict],
    empty_message: str,
) -> None:
    """
    Display a collection of recommendation items.
    """

    st.subheader(title)

    if not items:
        st.caption(empty_message)
        return

    for index, item in enumerate(
        items,
        start=1,
    ):
        item_title = item.get(
            "title",
            f"Item {index}",
        )

        importance = item.get(
            "importance",
            "medium",
        ).lower()

        importance_label = IMPORTANCE_LABELS.get(
            importance,
            "Medium importance",
        )

        with st.expander(
            f"{index}. {item_title} — {importance_label}"
        ):
            explanation = item.get(
                "explanation",
                "",
            )

            if explanation:
                st.write(explanation)

            cv_evidence = item.get(
                "cv_evidence",
                "",
            )

            if cv_evidence:
                st.write("**CV evidence:**")
                st.write(cv_evidence)

            job_evidence = item.get(
                "job_evidence",
                "",
            )

            if job_evidence:
                st.write(
                    "**Job-description evidence:**"
                )
                st.write(job_evidence)


def render_suggested_bullets(
    bullets: list[dict],
) -> None:
    """
    Display AI-suggested CV bullets.
    """

    st.subheader(
        "Suggested CV Bullet Improvements"
    )

    if not bullets:
        st.caption(
            "No evidence-based bullet improvements "
            "were generated."
        )
        return

    st.warning(
        "Use a suggested bullet only when it accurately "
        "describes work you genuinely completed."
    )

    for index, bullet in enumerate(
        bullets,
        start=1,
    ):
        st.write(
            f"**Suggestion {index}**"
        )

        st.write(
            "**Existing CV evidence:**"
        )

        st.write(
            bullet.get(
                "original_evidence",
                "",
            )
        )

        st.write(
            "**Suggested bullet:**"
        )

        st.code(
            bullet.get(
                "suggested_bullet",
                "",
            ),
            language=None,
        )

        related_requirement = bullet.get(
            "related_requirement",
            "",
        )

        if related_requirement:
            st.write(
                "**Related job requirement:**"
            )
            st.write(
                related_requirement
            )

        st.divider()


def render_ai_recommendations(
    recommendations: dict,
) -> None:
    """
    Display the complete AI recommendation report.
    """

    st.divider()
    st.header("AI CV Recommendations")

    st.caption(
        "These suggestions are generated by a local AI model. "
        "Verify every suggestion before changing your CV."
    )

    overall_summary = recommendations.get(
        "overall_summary",
        "",
    )

    if overall_summary:
        st.info(overall_summary)

    warnings = recommendations.get(
        "important_warnings",
        [],
    )

    if warnings:
        st.subheader("Important Warnings")

        for warning in warnings:
            st.warning(warning)

    tab1, tab2, tab3, tab4 = st.tabs(
        [
            "Strong Matches",
            "Missing Requirements",
            "Weak Evidence",
            "Improvements",
        ]
    )

    with tab1:
        render_recommendation_items(
            title="Strong Matches",
            items=recommendations.get(
                "strong_matches",
                [],
            ),
            empty_message=(
                "No strong matches were generated."
            ),
        )

    with tab2:
        render_recommendation_items(
            title="Requirements Not Evidenced in the CV",
            items=recommendations.get(
                "missing_requirements",
                [],
            ),
            empty_message=(
                "No missing requirements were identified."
            ),
        )

    with tab3:
        render_recommendation_items(
            title="Skills With Weak Evidence",
            items=recommendations.get(
                "weakly_evidenced_skills",
                [],
            ),
            empty_message=(
                "No weakly evidenced skills were identified."
            ),
        )

    with tab4:
        render_recommendation_items(
            title="CV Improvement Suggestions",
            items=recommendations.get(
                "improvement_suggestions",
                [],
            ),
            empty_message=(
                "No improvement suggestions were generated."
            ),
        )

    render_suggested_bullets(
        recommendations.get(
            "suggested_bullets",
            [],
        )
    )