import streamlit as st

from services.cv_section_improver import (
    create_section_improvement,
)


IMPORTANCE_LABELS = {
    "high": "High importance",
    "medium": "Medium importance",
    "low": "Low importance",
}


def render_recommendation_items(
    title: str,
    items: list[dict],
    empty_message: str,
) -> None:
    """
    Display a collection of recommendation items.
    """

    st.subheader(title)

    if not items:
        st.caption(empty_message)
        return

    for index, item in enumerate(
        items,
        start=1,
    ):
        item_title = item.get(
            "title",
            f"Item {index}",
        )

        importance = item.get(
            "importance",
            "medium",
        ).lower()

        importance_label = IMPORTANCE_LABELS.get(
            importance,
            "Medium importance",
        )

        with st.expander(
            f"{index}. {item_title} — {importance_label}"
        ):
            explanation = item.get(
                "explanation",
                "",
            )

            if explanation:
                st.write(explanation)

            cv_evidence = item.get(
                "cv_evidence",
                "",
            )

            if cv_evidence:
                st.write("**CV evidence:**")
                st.write(cv_evidence)

            job_evidence = item.get(
                "job_evidence",
                "",
            )

            if job_evidence:
                st.write(
                    "**Job-description evidence:**"
                )
                st.write(job_evidence)


def render_suggested_bullets(
    bullets: list[dict],
) -> None:
    """
    Display AI-suggested CV bullets.
    """

    st.subheader(
        "Suggested CV Bullet Improvements"
    )

    if not bullets:
        st.caption(
            "No evidence-based bullet improvements "
            "were generated."
        )
        return

    st.warning(
        "Use a suggested bullet only when it accurately "
        "describes work you genuinely completed."
    )

    for index, bullet in enumerate(
        bullets,
        start=1,
    ):
        st.write(
            f"**Suggestion {index}**"
        )

        st.write(
            "**Existing CV evidence:**"
        )

        st.write(
            bullet.get(
                "original_evidence",
                "",
            )
        )

        st.write(
            "**Suggested bullet:**"
        )

        st.code(
            bullet.get(
                "suggested_bullet",
                "",
            ),
            language=None,
        )

        related_requirement = bullet.get(
            "related_requirement",
            "",
        )

        if related_requirement:
            st.write(
                "**Related job requirement:**"
            )
            st.write(
                related_requirement
            )

        st.divider()


def render_ai_recommendations(
    recommendations: dict,
) -> None:
    """
    Display the complete AI recommendation report.
    """

    st.divider()
    st.header("AI CV Recommendations")

    st.caption(
        "These suggestions are generated by a local AI model. "
        "Verify every suggestion before changing your CV."
    )

    overall_summary = recommendations.get(
        "overall_summary",
        "",
    )

    if overall_summary:
        st.info(overall_summary)

    warnings = recommendations.get(
        "important_warnings",
        [],
    )

    if warnings:
        st.subheader("Important Warnings")

        for warning in warnings:
            st.warning(warning)

    tab1, tab2, tab3, tab4 = st.tabs(
        [
            "Strong Matches",
            "Missing Requirements",
            "Weak Evidence",
            "Improvements",
        ]
    )

    with tab1:
        render_recommendation_items(
            title="Strong Matches",
            items=recommendations.get(
                "strong_matches",
                [],
            ),
            empty_message=(
                "No strong matches were generated."
            ),
        )

    with tab2:
        render_recommendation_items(
            title="Requirements Not Evidenced in the CV",
            items=recommendations.get(
                "missing_requirements",
                [],
            ),
            empty_message=(
                "No missing requirements were identified."
            ),
        )

    with tab3:
        render_recommendation_items(
            title="Skills With Weak Evidence",
            items=recommendations.get(
                "weakly_evidenced_skills",
                [],
            ),
            empty_message=(
                "No weakly evidenced skills were identified."
            ),
        )

    with tab4:
        render_recommendation_items(
            title="CV Improvement Suggestions",
            items=recommendations.get(
                "improvement_suggestions",
                [],
            ),
            empty_message=(
                "No improvement suggestions were generated."
            ),
        )

    render_suggested_bullets(
        recommendations.get(
            "suggested_bullets",
            [],
        )
    )

def render_cv_section_improver() -> None:
    """
    Render one-click CV section improvement.
    """

    st.divider()
    st.header(
        "One-Click CV Section Improver"
    )

    st.caption(
        "Paste one section from your CV, improve it for the current job, "
        "and compare the original with the revised version. "
        "Nothing is overwritten automatically."
    )

    cv_text = st.session_state.get(
        "final_cv_text",
        "",
    ) or ""

    job_text = st.session_state.get(
        "final_job_text",
        "",
    ) or ""

    if not cv_text or not job_text:
        st.info(
            "Run a CV and job analysis first."
        )
        return

    section_col, language_col = st.columns(2)

    with section_col:
        section_name = st.selectbox(
            "CV section",
            [
                "Professional Summary",
                "Skills",
                "Experience",
                "Projects",
            ],
            key="section_improver_name",
        )

    with language_col:
        language = st.selectbox(
            "Output language",
            [
                "English",
                "German",
            ],
            key="section_improver_language",
        )

    section_text = st.text_area(
        "Paste the exact section you want to improve",
        height=220,
        key="section_improver_input",
        placeholder=(
            "Paste only the selected section from your CV here..."
        ),
    )

    if st.button(
        "Improve This Section",
        type="primary",
        use_container_width=True,
        key="improve_cv_section_button",
    ):
        if not section_text.strip():
            st.error(
                "Please paste the section text first."
            )
        else:
            try:
                with st.spinner(
                    "Improving the selected CV section..."
                ):
                    result = create_section_improvement(
                        cv_text=cv_text,
                        job_text=job_text,
                        section_name=section_name,
                        section_text=section_text,
                        language=language,
                    )

                st.session_state[
                    "cv_section_improvement_result"
                ] = result

                st.success(
                    "Section improvement completed."
                )

            except Exception as error:
                st.error(
                    "Section improvement failed."
                )
                st.code(
                    f"{type(error).__name__}: {error}"
                )

    result = st.session_state.get(
        "cv_section_improvement_result",
        {},
    ) or {}

    if not result:
        return

    warnings = result.get(
        "warnings",
        [],
    )

    for warning in warnings:
        st.warning(
            warning
        )

    st.subheader(
        "Before and After"
    )

    before_col, after_col = st.columns(2)

    with before_col:
        st.write(
            "### Before"
        )
        st.text_area(
            "Original section",
            value=result.get(
                "original_text",
                "",
            ),
            height=350,
            disabled=True,
            key="section_improver_before",
        )

    with after_col:
        st.write(
            "### After"
        )
        improved_text = st.text_area(
            "Improved section",
            value=result.get(
                "improved_text",
                "",
            ),
            height=350,
            key="section_improver_after",
        )

    explanation = result.get(
        "explanation",
        "",
    )

    if explanation:
        st.subheader(
            "Why It Changed"
        )
        st.info(
            explanation
        )

    changes_made = result.get(
        "changes_made",
        [],
    )

    if changes_made:
        st.subheader(
            "Changes Made"
        )

        for index, change in enumerate(
            changes_made,
            start=1,
        ):
            st.write(
                f"**{index}.** {change}"
            )

    st.download_button(
        "Download Improved Section",
        data=improved_text.encode(
            "utf-8"
        ),
        file_name=(
            "improved_cv_section.txt"
        ),
        mime="text/plain",
        use_container_width=True,
        key="download_improved_cv_section",
    )

    st.warning(
        "Review every sentence. Keep only statements that are "
        "fully accurate and supported by your real experience."
    )
